src/Entity/Logbook.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LogbookRepository")
 */
class Logbook
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=false)
     */
    private $userId;

    /**
     * @ORM\Column(type="integer")
     */
    private $brief_nr;

    /**
     * @ORM\Column(type="datetime")
     */
    private $datum;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=false)
     */
    private $chauffeurId;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Truck")
     * @ORM\JoinColumn(nullable=false)
     */
    private $truckId;

    /**
     * @ORM\Column(type="integer")
     */
    private $kubs;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $laadplaats;

    /**
     * @ORM\Column(type="time")
     */
    private $vertrektijd;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $bestemming;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $evenement;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserId(): ?User
    {
        return $this->userId;
    }

    public function setUserId(?User $userId): self
    {
        $this->userId = $userId;

        return $this;
    }

    public function getBriefNr(): ?int
    {
        return $this->brief_nr;
    }

    public function setBriefNr(int $brief_nr): self
    {
        $this->brief_nr = $brief_nr;

        return $this;
    }

    public function getDatum(): ?\DateTimeInterface
    {
        return $this->datum;
    }

    public function setDatum(\DateTimeInterface $datum): self
    {
        $this->datum = $datum;

        return $this;
    }

    public function getChauffeurId(): ?User
    {
        return $this->chauffeurId;
    }

    public function setChauffeurId(?User $chauffeurId): self
    {
        $this->chauffeurId = $chauffeurId;

        return $this;
    }

    public function getTruckId(): ?Truck
    {
        return $this->truckId;
    }

    public function setTruckId(?Truck $truckId): self
    {
        $this->truckId = $truckId;

        return $this;
    }

    public function getKubs(): ?int
    {
        return $this->kubs;
    }

    public function setKubs(int $kubs): self
    {
        $this->kubs = $kubs;

        return $this;
    }

    public function getLaadplaats(): ?string
    {
        return $this->laadplaats;
    }

    public function setLaadplaats(string $laadplaats): self
    {
        $this->laadplaats = $laadplaats;

        return $this;
    }

    public function getVertrektijd(): ?\DateTimeInterface
    {
        return $this->vertrektijd;
    }

    public function setVertrektijd(\DateTimeInterface $vertrektijd): self
    {
        $this->vertrektijd = $vertrektijd;

        return $this;
    }

    public function getBestemming(): ?string
    {
        return $this->bestemming;
    }

    public function setBestemming(string $bestemming): self
    {
        $this->bestemming = $bestemming;

        return $this;
    }

    public function getEvenement(): ?string
    {
        return $this->evenement;
    }

    public function setEvenement(string $evenement): self
    {
        $this->evenement = $evenement;

        return $this;
    }
}

src/Form/LogbookType.php
<?php

namespace App\Form;

use App\Entity\Logbook;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LogbookType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('brief_nr')
            ->add('datum')
            ->add('kubs')
            ->add('laadplaats')
            ->add('vertrektijd')
            ->add('bestemming')
            ->add('evenement')
            ->add('userId')
            ->add('chauffeurId')
            ->add('truckId')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Logbook::class,
        ]);
    }
}

src/Controller/LogbookController.php
<?php

namespace App\Controller;

use App\Entity\Logbook;
use App\Form\LogbookType;
use App\Repository\LogbookRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/logbook")
 */
class LogbookController extends AbstractController
{
    /**
     * @Route("/", name="logbook_index", methods={"GET"})
     */
    public function index(LogbookRepository $logbookRepository): Response
    {
        return $this->render('logbook/index.html.twig', [
            'logbooks' => $logbookRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="logbook_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $logbook = new Logbook();
        $form = $this->createForm(LogbookType::class, $logbook);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($logbook);
            $entityManager->flush();

            return $this->redirectToRoute('logbook_index');
        }

        return $this->render('logbook/new.html.twig', [
            'logbook' => $logbook,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="logbook_show", methods={"GET"})
     */
    public function show(Logbook $logbook): Response
    {
        return $this->render('logbook/show.html.twig', [
            'logbook' => $logbook,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="logbook_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Logbook $logbook): Response
    {
        $form = $this->createForm(LogbookType::class, $logbook);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('logbook_index', [
                'id' => $logbook->getId(),
            ]);
        }

        return $this->render('logbook/edit.html.twig', [
            'logbook' => $logbook,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="logbook_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Logbook $logbook): Response
    {
        if ($this->isCsrfTokenValid('delete'.$logbook->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($logbook);
            $entityManager->flush();
        }

        return $this->redirectToRoute('logbook_index');
    }
}

templates/logbook/_delete_form.html.twig
<form method="post" action="{{ path('logbook_delete', {'id': logbook.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ logbook.id) }}">
    <button class="btn">Delete</button>
</form>

templates/logbook/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/logbook/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Logbook{% endblock %}

{% block body %}
    <h1>Edit Logbook</h1>

    {{ include('logbook/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('logbook_index') }}">back to list</a>

    {{ include('logbook/_delete_form.html.twig') }}
{% endblock %}

templates/logbook/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Logbook index{% endblock %}

{% block body %}
    <h1>Logbook index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Brief_nr</th>
                <th>Datum</th>
                <th>Kubs</th>
                <th>Laadplaats</th>
                <th>Vertrektijd</th>
                <th>Bestemming</th>
                <th>Evenement</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for logbook in logbooks %}
            <tr>
                <td>{{ logbook.id }}</td>
                <td>{{ logbook.briefNr }}</td>
                <td>{{ logbook.datum ? logbook.datum|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ logbook.kubs }}</td>
                <td>{{ logbook.laadplaats }}</td>
                <td>{{ logbook.vertrektijd ? logbook.vertrektijd|date('H:i:s') : '' }}</td>
                <td>{{ logbook.bestemming }}</td>
                <td>{{ logbook.evenement }}</td>
                <td>
                    <a href="{{ path('logbook_show', {'id': logbook.id}) }}">show</a>
                    <a href="{{ path('logbook_edit', {'id': logbook.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('logbook_new') }}">Create new</a>
{% endblock %}

templates/logbook/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Logbook{% endblock %}

{% block body %}
    <h1>Create new Logbook</h1>

    {{ include('logbook/_form.html.twig') }}

    <a href="{{ path('logbook_index') }}">back to list</a>
{% endblock %}

templates/logbook/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Logbook{% endblock %}

{% block body %}
    <h1>Logbook</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ logbook.id }}</td>
            </tr>
            <tr>
                <th>Brief_nr</th>
                <td>{{ logbook.briefNr }}</td>
            </tr>
            <tr>
                <th>Datum</th>
                <td>{{ logbook.datum ? logbook.datum|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Kubs</th>
                <td>{{ logbook.kubs }}</td>
            </tr>
            <tr>
                <th>Laadplaats</th>
                <td>{{ logbook.laadplaats }}</td>
            </tr>
            <tr>
                <th>Vertrektijd</th>
                <td>{{ logbook.vertrektijd ? logbook.vertrektijd|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Bestemming</th>
                <td>{{ logbook.bestemming }}</td>
            </tr>
            <tr>
                <th>Evenement</th>
                <td>{{ logbook.evenement }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('logbook_index') }}">back to list</a>

    <a href="{{ path('logbook_edit', {'id': logbook.id}) }}">edit</a>

    {{ include('logbook/_delete_form.html.twig') }}
{% endblock %}